AllCops:
  Include:
    - '**/Rakefile'
    - 'lib/**/*'
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
Style/HashSyntax:
  EnforcedStyle: ruby18
  SupportedStyles:
    - ruby19
    - ruby18
    - hash_rockets
Style/BracesAroundHashParameters:
  EnforcedStyle: braces
  SupportedStyles:
    - braces
    - no_braces
