AllCops:
  Include:
    - 'lib/**/*'
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'bin/**/*'
    - 'build/**/*'
    - 'tmp/**/*'
    - 'Rakefile'
    - '**/Rakefile'
Style/HashSyntax:
  EnforcedStyle: ruby18
  SupportedStyles:
    - ruby19
    - ruby18
    - hash_rockets
Style/BracesAroundHashParameters:
  EnforcedStyle: braces
  SupportedStyles:
    - braces
    - no_braces
Style/GlobalVars:
  Enabled: false
MethodLength:
  Enabled: false
LineLength:
  Max: 100
